apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama
        image: rkg1983/llama:6230f0ca41be29f14681856b2b1ed8500ce222cf
        ports:
        - containerPort: 8080
