apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama
        image: rkg1983/llama:e8f2bc4a53ea072c07659843e019774bb1e26b7c
        ports:
        - containerPort: 8080
