apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama
        image: rkg1983/llama:c8dc36b6aa8b9bdc06c53e34ac1630873aa16d62
        ports:
        - containerPort: 8080
